/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagesSettingsRouteImport } from './routes/pages/settings'
import { Route as PagesSearchRouteImport } from './routes/pages/search'
import { Route as PagesScheduleRouteImport } from './routes/pages/schedule'
import { Route as PagesReviewRouteImport } from './routes/pages/review'
import { Route as PagesNotifcationRouteImport } from './routes/pages/notifcation'
import { Route as PagesLoginRouteImport } from './routes/pages/login'
import { Route as PagesInvoiceRouteImport } from './routes/pages/invoice'
import { Route as PagesDashboardRouteImport } from './routes/pages/dashboard'
import { Route as PagesCreatorRouteImport } from './routes/pages/creator'
import { Route as PagesCollaborationRouteImport } from './routes/pages/collaboration'
import { Route as PagesClientRouteImport } from './routes/pages/client'

const PagesSettingsRoute = PagesSettingsRouteImport.update({
  id: '/pages/settings',
  path: '/pages/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSearchRoute = PagesSearchRouteImport.update({
  id: '/pages/search',
  path: '/pages/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesScheduleRoute = PagesScheduleRouteImport.update({
  id: '/pages/schedule',
  path: '/pages/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesReviewRoute = PagesReviewRouteImport.update({
  id: '/pages/review',
  path: '/pages/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesNotifcationRoute = PagesNotifcationRouteImport.update({
  id: '/pages/notifcation',
  path: '/pages/notifcation',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesLoginRoute = PagesLoginRouteImport.update({
  id: '/pages/login',
  path: '/pages/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesInvoiceRoute = PagesInvoiceRouteImport.update({
  id: '/pages/invoice',
  path: '/pages/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesDashboardRoute = PagesDashboardRouteImport.update({
  id: '/pages/dashboard',
  path: '/pages/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCreatorRoute = PagesCreatorRouteImport.update({
  id: '/pages/creator',
  path: '/pages/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCollaborationRoute = PagesCollaborationRouteImport.update({
  id: '/pages/collaboration',
  path: '/pages/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesClientRoute = PagesClientRouteImport.update({
  id: '/pages/client',
  path: '/pages/client',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/pages/client': typeof PagesClientRoute
  '/pages/collaboration': typeof PagesCollaborationRoute
  '/pages/creator': typeof PagesCreatorRoute
  '/pages/dashboard': typeof PagesDashboardRoute
  '/pages/invoice': typeof PagesInvoiceRoute
  '/pages/login': typeof PagesLoginRoute
  '/pages/notifcation': typeof PagesNotifcationRoute
  '/pages/review': typeof PagesReviewRoute
  '/pages/schedule': typeof PagesScheduleRoute
  '/pages/search': typeof PagesSearchRoute
  '/pages/settings': typeof PagesSettingsRoute
}
export interface FileRoutesByTo {
  '/pages/client': typeof PagesClientRoute
  '/pages/collaboration': typeof PagesCollaborationRoute
  '/pages/creator': typeof PagesCreatorRoute
  '/pages/dashboard': typeof PagesDashboardRoute
  '/pages/invoice': typeof PagesInvoiceRoute
  '/pages/login': typeof PagesLoginRoute
  '/pages/notifcation': typeof PagesNotifcationRoute
  '/pages/review': typeof PagesReviewRoute
  '/pages/schedule': typeof PagesScheduleRoute
  '/pages/search': typeof PagesSearchRoute
  '/pages/settings': typeof PagesSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/pages/client': typeof PagesClientRoute
  '/pages/collaboration': typeof PagesCollaborationRoute
  '/pages/creator': typeof PagesCreatorRoute
  '/pages/dashboard': typeof PagesDashboardRoute
  '/pages/invoice': typeof PagesInvoiceRoute
  '/pages/login': typeof PagesLoginRoute
  '/pages/notifcation': typeof PagesNotifcationRoute
  '/pages/review': typeof PagesReviewRoute
  '/pages/schedule': typeof PagesScheduleRoute
  '/pages/search': typeof PagesSearchRoute
  '/pages/settings': typeof PagesSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/pages/client'
    | '/pages/collaboration'
    | '/pages/creator'
    | '/pages/dashboard'
    | '/pages/invoice'
    | '/pages/login'
    | '/pages/notifcation'
    | '/pages/review'
    | '/pages/schedule'
    | '/pages/search'
    | '/pages/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pages/client'
    | '/pages/collaboration'
    | '/pages/creator'
    | '/pages/dashboard'
    | '/pages/invoice'
    | '/pages/login'
    | '/pages/notifcation'
    | '/pages/review'
    | '/pages/schedule'
    | '/pages/search'
    | '/pages/settings'
  id:
    | '__root__'
    | '/pages/client'
    | '/pages/collaboration'
    | '/pages/creator'
    | '/pages/dashboard'
    | '/pages/invoice'
    | '/pages/login'
    | '/pages/notifcation'
    | '/pages/review'
    | '/pages/schedule'
    | '/pages/search'
    | '/pages/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PagesClientRoute: typeof PagesClientRoute
  PagesCollaborationRoute: typeof PagesCollaborationRoute
  PagesCreatorRoute: typeof PagesCreatorRoute
  PagesDashboardRoute: typeof PagesDashboardRoute
  PagesInvoiceRoute: typeof PagesInvoiceRoute
  PagesLoginRoute: typeof PagesLoginRoute
  PagesNotifcationRoute: typeof PagesNotifcationRoute
  PagesReviewRoute: typeof PagesReviewRoute
  PagesScheduleRoute: typeof PagesScheduleRoute
  PagesSearchRoute: typeof PagesSearchRoute
  PagesSettingsRoute: typeof PagesSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pages/settings': {
      id: '/pages/settings'
      path: '/pages/settings'
      fullPath: '/pages/settings'
      preLoaderRoute: typeof PagesSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/search': {
      id: '/pages/search'
      path: '/pages/search'
      fullPath: '/pages/search'
      preLoaderRoute: typeof PagesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/schedule': {
      id: '/pages/schedule'
      path: '/pages/schedule'
      fullPath: '/pages/schedule'
      preLoaderRoute: typeof PagesScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/review': {
      id: '/pages/review'
      path: '/pages/review'
      fullPath: '/pages/review'
      preLoaderRoute: typeof PagesReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/notifcation': {
      id: '/pages/notifcation'
      path: '/pages/notifcation'
      fullPath: '/pages/notifcation'
      preLoaderRoute: typeof PagesNotifcationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/login': {
      id: '/pages/login'
      path: '/pages/login'
      fullPath: '/pages/login'
      preLoaderRoute: typeof PagesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/invoice': {
      id: '/pages/invoice'
      path: '/pages/invoice'
      fullPath: '/pages/invoice'
      preLoaderRoute: typeof PagesInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/dashboard': {
      id: '/pages/dashboard'
      path: '/pages/dashboard'
      fullPath: '/pages/dashboard'
      preLoaderRoute: typeof PagesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/creator': {
      id: '/pages/creator'
      path: '/pages/creator'
      fullPath: '/pages/creator'
      preLoaderRoute: typeof PagesCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/collaboration': {
      id: '/pages/collaboration'
      path: '/pages/collaboration'
      fullPath: '/pages/collaboration'
      preLoaderRoute: typeof PagesCollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/client': {
      id: '/pages/client'
      path: '/pages/client'
      fullPath: '/pages/client'
      preLoaderRoute: typeof PagesClientRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PagesClientRoute: PagesClientRoute,
  PagesCollaborationRoute: PagesCollaborationRoute,
  PagesCreatorRoute: PagesCreatorRoute,
  PagesDashboardRoute: PagesDashboardRoute,
  PagesInvoiceRoute: PagesInvoiceRoute,
  PagesLoginRoute: PagesLoginRoute,
  PagesNotifcationRoute: PagesNotifcationRoute,
  PagesReviewRoute: PagesReviewRoute,
  PagesScheduleRoute: PagesScheduleRoute,
  PagesSearchRoute: PagesSearchRoute,
  PagesSettingsRoute: PagesSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
